//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SweetsCompleteStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int product_id { get; set; }
        public string sku { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public decimal price { get; set; }
        public int special { get; set; }
        public string link { get; set; }
    }
}
