//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SweetsCompleteApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class fixed_purchases
    {
        public int purchase_id { get; set; }
        public string trans_id { get; set; }
        public int product_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> sale_price { get; set; }
    
        public virtual member member { get; set; }
        public virtual product product { get; set; }
    }
}
