//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SweetsCompleteApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public member()
        {
            this.fixed_purchases = new HashSet<fixed_purchases>();
        }
    
        public int user_id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state_province { get; set; }
        public string postal_code { get; set; }
        public string country { get; set; }
        public string phone { get; set; }
        public decimal balance { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<fixed_purchases> fixed_purchases { get; set; }
    }
}
